# Generated by Django 4.0.2 on 2022-05-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToastSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Close_Button', models.BooleanField(blank=True, default=False)),
                ('Add_behavior_click', models.BooleanField(blank=True, default=False)),
                ('Progress_Bar', models.BooleanField(blank=True, default=False)),
                ('Prevent_Duplicates', models.BooleanField(blank=True, default=False)),
                ('Newest_on_top', models.BooleanField(blank=True, default=False)),
                ('Position', models.CharField(choices=[('toast-top-right', 'Top Right'), ('toast-top-left', 'Top Left'), ('toast-top-center', 'Top Center'), ('toast-top-full-width', 'Top Full Width'), ('toast-bottom-right', 'Bottom Right'), ('toast-bottom-left', 'Bottom Left'), ('toast-bottom-full-width', 'Bottom Full Width'), ('toast-bottom-center', 'Bottom Center')], default='toast-top-right', max_length=50)),
                ('showEasing', models.CharField(choices=[('swing', 'swing'), ('linear', 'linear')], default='swing', max_length=50)),
                ('hideEasing', models.CharField(choices=[('swing', 'swing'), ('linear', 'linear')], default='linear', max_length=50)),
                ('showMethod', models.CharField(choices=[('show', 'show'), ('fadeIn', 'fadeIn'), ('slideDown', 'slideDown')], default='fadeIn', max_length=50)),
                ('hideMethod', models.CharField(choices=[('hide', 'hide'), ('fadeOut', 'fadeOut'), ('slideUp', 'slideUp')], default='fadeOut', max_length=50)),
                ('showDuratio', models.PositiveBigIntegerField(default=300)),
                ('hideDuration', models.PositiveBigIntegerField(default=1000)),
                ('timeOut', models.PositiveBigIntegerField(default=5000)),
                ('extendedTimeOut', models.PositiveBigIntegerField(default=1000)),
            ],
        ),
    ]
