# Generated by Django 4.0.2 on 2022-05-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aj_toast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toastsettings',
            name='Add_behavior_click',
            field=models.BooleanField(blank=True, default='false'),
        ),
        migrations.AlterField(
            model_name='toastsettings',
            name='Close_Button',
            field=models.BooleanField(blank=True, default='false'),
        ),
        migrations.AlterField(
            model_name='toastsettings',
            name='Newest_on_top',
            field=models.BooleanField(blank=True, default='false'),
        ),
        migrations.AlterField(
            model_name='toastsettings',
            name='Prevent_Duplicates',
            field=models.BooleanField(blank=True, default='false'),
        ),
        migrations.AlterField(
            model_name='toastsettings',
            name='Progress_Bar',
            field=models.BooleanField(blank=True, default='false'),
        ),
    ]
